import Footer from "@/components/Footer";
// import Navbar from "@/components/Navbar";
// import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import { ReactNode } from "react";

import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Alexis Ngaing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {/* <Navbar /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
